config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stores
  resources :books
  resources :assignments
  get '/home', to: 'static_pages#home'
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
	belongs_to :book
	belongs_to :store

	validates_uniqueness_of :store_id, scope: :book_id
	validates :quantity, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :assignments
  has_many :stores, through: :assignments
  validates :title, presence: true, length: { maximum: 80 },
                    uniqueness: { case_sensitive: false }
  validates :author, presence: true, length: { maximum: 80 }
  validates :year, presence: true, length: { maximum: 4 }

  def to_s
    "#{title} - #{author}"
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :assignments
  has_many :books, through: :assignments
  validates :codename, presence: true, length: { maximum: 6 },
                       uniqueness: { case_sensitive: false }
  validates :address, presence: true, length: { maximum: 120 }
  validates :phone, presence: true, length: { maximum: 20 }

  def to_s
    "#{codename} - #{address}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  before_action :set_lists

  def index
    @assignments = if params[:term]
      Assignment.joins(:book, :store).where('stores.codename LIKE :search OR stores.address LIKE :search OR books.title LIKE :search OR books.author LIKE :search OR books.year LIKE :search', search: "%#{params[:term]}%")
    else
      @assignments = Assignment.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
    end
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)

    if @assignment.save
      flash[:success] = "Book added to store"
      redirect_to assignments_path
    else
      render 'new'
    end
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    @assignment.update_attributes(assignment_params)
    flash[:primary] = "Information updated"
    redirect_to assignments_path
  end

  def destroy
    @assignments = Assignment.find(params[:id])
    @assignments.destroy
    flash[:danger] = "Books deleted from stores"
    redirect_to assignments_path
  end

  private

  def assignment_params
    params.require(:assignment).permit(:store_id, :book_id, :quantity, :term)
  end

  def set_lists
    @store_list = Store.all.map { |store| [ store.to_s, store.id ] }
    @book_list = Book.all.map { |book| [ book.to_s, book.id ] }
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = "Book added"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    @store_list = Store.all.map { |store| [ store.to_s, store.id ] }
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes(book_params)
    flash[:primary] = "Book information updated"
    redirect_to books_path
  end

  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    flash[:danger] = "Book deleted"
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :year, :term, :quantity, :store_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def index
    @stores = Store.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
  end
  
  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)

    if @store.save
    	flash[:success] = "Store location added"
      redirect_to stores_path
    else
      render 'new'
    end
  end

  def show
    @store = Store.find(params[:id])
  end

  def edit
  	@store = Store.find(params[:id])
  end

  def update
  	@store = Store.find(params[:id])
  	@store.update_attributes(store_params)
  	flash[:primary] = "Store information updated"
    redirect_to stores_path
  end

  def destroy
    @stores = Store.find(params[:id])
    @stores.destroy
    flash[:danger] = "Store location deleted"
    redirect_to stores_path
  end

  private

  def store_params
    params.require(:store).permit(:codename, :address, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/assignments/_form.html.slim
= form_for(@assignment) do |f|
  = render 'shared/assignment_error_messages'
  = f.label :store_id, "Store"
  = f.select :store_id, @store_list, {}, {:class => "form-control"}
  = f.label :book_id, "Book"
  = f.select :book_id, @book_list, {}, {:class => "form-control"}
  = f.label :quantity
  = f.number_field :quantity, :class => "form-control", :step => 1, :min => 1
  = submit_tag "Save", :class => "btn btn-primary form-control", :id => "save"

app/views/assignments/edit.html.slim
div [class="col-12 col-lg-12"]
  .row [class="justify-content-lg-center"]
    div [class="col-12 col-lg-8"]
      h1 Edit book info
      hr
      = render 'form'

app/views/assignments/index.html.slim
h1 Add a book to a store
hr
div [class="row justify-content-between"]
  .col-8
    = link_to 'Assign book to a store', new_assignment_path, class: 'btn btn-success'
  .col-4
    = form_tag(assignments_path, {class: 'form-inline', method: :get}) do
      div [class="form-group"]
      = text_field_tag(:term, "" , :class => "form-control", :placeholder => "Search...")
      = submit_tag "Search", :class => "btn btn-secondary form-control", :id => "searchBTN", name: nil
table [class="table"]
  thead [class="thead-dark"]
    tr
      th ID
      th Store
      th Book
      th Quantity
      th Edit
      th Delete
  tbody
    - @assignments.each do |assignment|
      tr
        th = link_to assignment.id, assignment
        td = assignment.store
        td = assignment.book
        td = assignment.quantity
        td = link_to "Edit", edit_assignment_path(assignment), method: :get
        td = link_to "Delete", assignment, method: :delete, data: { confirm: "Are you sure you want to delete this relationship?" }
- unless params[:term]
  = will_paginate(@books, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "pagination justify-content-center")

app/views/assignments/new.html.slim
h1 New Assignment
hr
  = render 'form'

app/views/assignments/show.html.slim
.row
  div [class="col-12 col-lg-12"]
    h1 Books in stores
    hr
    .card
      .card-body
        h5 Store: 
        p #{@assignment.store} 
        h5 Book:
        p #{@assignment.book}
        h5 Quantity:
        p #{@assignment.quantity}
    br
    h5 = link_to 'Go back', assignments_path

app/views/books/_form.html.slim
= form_for(@book) do |f|
  = render 'shared/book_error_messages'
  = f.label :title
  = f.text_field :title, :class => "form-control"
  = f.label :author
  = f.text_field :author, :class => "form-control"
  = f.label :year
  = f.text_field :year, :class => "form-control"
  = submit_tag "Save", :class => "btn btn-primary form-control", :id => "save"

app/views/books/edit.html.slim
.row
div [class="col-12 col-lg-12"]
  .row [class="justify-content-lg-center"]
    div [class="col-12 col-lg-8"]
      h1 Edit book info
      hr
      = render 'form'

app/views/books/index.html.slim
h1 Books
hr
= link_to 'Add new book', new_book_path, class: 'btn btn-success' 
table [class="table"]
  thead [class="thead-dark"]
    tr
      th ID
      th Title
      th Author
      th Year
      th Edit
      th Delete
  tbody
    - @books.each do |book|
      tr
        th = link_to book.id, book
        td = book.title
        td = book.author
        td = book.year
        td = link_to "Edit ", edit_book_path(book), method: :get
        td = link_to "Delete", book, method: :delete, data: { confirm: "Are you sure you want to delete this book?" }
= will_paginate(@books, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "pagination justify-content-center")

app/views/books/new.html.slim
.row
div [class="col-12 col-lg-12"]
  .row [class="justify-content-lg-center"]
    div [class="col-12 col-lg-8"]
      h1 Add new book
      hr
      = render 'form'

app/views/books/show.html.slim
.row
  div [class="col-12 col-lg-12"]
    h1 Book
    hr
    .card
      .card-body
        h5 Title: 
        p #{@book.title} 
        h5 Author:
        p #{@book.author}
        h5 Year:
        p #{@book.year}
    br
    h5 = link_to 'Go back', books_path
        

app/views/layouts/application.html.slim
doctype html
html
  head
    title BookStore
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    header
      nav [class="navbar navbar-expand-lg navbar-dark bg-dark"]
        = link_to 'Book Store', home_path, class: 'navbar-brand'
        button [class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"]
          span [class="navbar-toggler-icon"]
        div [class="collapse navbar-collapse", id="navbarNav"]
          ul [class="navbar-nav"]
            li [class="nav-item"]
              = link_to 'Stores', stores_path, class: 'nav-link'
            li [class="nav-item"]
              = link_to 'Books', books_path, class: 'nav-link'
            li [class="nav-item"]
              = link_to 'Assignments', assignments_path, class: 'nav-link'
    .container
      - flash.each do |key, value|
        div [class="alert alert-#{key}"]
          button [class="close" data-dismiss="alert"] X
          = value
      = yield

app/views/shared/_assignment_error_messages.html.slim
- if @assignment.errors.any?
  #error_explanation
    div [class="alert alert-danger"]
      span The form contains #{pluralize(@assignment.errors.count, "error")}
    ul
      - @assignment.errors.full_messages.each do |msg|
        li.text-danger = msg

app/views/shared/_book_error_messages.html.slim
- if @book.errors.any?
  #error_explanation
    div [class="alert alert-danger"]
      span The form contains #{pluralize(@book.errors.count, "error")}
    ul
      - @book.errors.full_messages.each do |msg|
        li.text-danger = msg

app/views/shared/_error_messages.html.slim
- if @store.errors.any?
  #error_explanation
    div [class="alert alert-danger"]
      span The form contains #{pluralize(@store.errors.count, "error")}
    ul
      - @store.errors.full_messages.each do |msg|
        li.text-danger = msg

app/views/static_pages/home.html.slim
.row
div [class="col-12"]
  .jumbotron
    h1 [class="display-4"] Hello, user!
    p [class="lead"] This is an application made with Ruby on Rails to manage a book store.
    hr [class="my-4"]
    p You can manage both book stores and books with this app.

app/views/stores/_form.html.slim
= form_for(@store) do |f|
  = render 'shared/error_messages'
  = f.label :codename
  = f.text_field :codename, :class => "form-control"
  = f.label :address
  = f.text_field :address, :class => "form-control"
  = f.label :phone
  = f.telephone_field :phone, :class => "form-control"
  = submit_tag "Save", :class => "btn btn-primary form-control", :id => "save"

app/views/stores/edit.html.slim
.row
div [class="col-12 col-lg-12"]
  .row [class="justify-content-lg-center"]
    div [class="col-12 col-lg-8"]
      h1 Update store information
      hr
      = render 'form'

app/views/stores/index.html.slim
h1 Stores
hr
= link_to 'Add new store', new_store_path, class: 'btn btn-success'
table [class="table"]
  thead [class="thead-dark"]
    tr
      th ID
      th Codename
      th Address
      th Phone
      th Edit
      th Delete
  tbody
    - @stores.each do |store|
      tr
        th = link_to store.id, store
        td = store.codename
        td = store.address
        td = store.phone
        td = link_to "Edit ", edit_store_path(store), method: :get
        td = link_to "Delete", store, method: :delete, data: { confirm: "Are you sure you want to delete this store?" }

= will_paginate(@stores, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "pagination justify-content-center")

app/views/stores/new.html.slim
.row
div [class="col-12 col-lg-12"]
  .row [class="justify-content-lg-center"]
    div [class="col-12 col-lg-8"]
      h1 Add new store
      hr
      = render 'form'

app/views/stores/show.html.slim
.row
  div [class="col-12 col-lg-12"]
    h1 Store
    hr
    .card
      .card-body
        h5 Store:
        p #{@store.codename} 
        h5 Address:
        p #{@store.address}
        h5 Phone:
        p #{@store.phone}
    br
    h5 = link_to 'Go back', stores_path
        